### ISSUE TITLE
Share Grafana Dashboard

### ISSUE THREAD

**Issue by soloam** [bartbutenaers/node-red-contrib-gc#1]
Hello, Are the last grafs from grafana? Can you share your grafana JSON? What are you using? The Before Data or the After?

Thank You

**Comment by bartbutenaers** [comment]
Hi @soloam,
No I just copied some images from the internet to explain how the garbage collectuon works.  So I won't be able to help you with this.
Best you can do is ask your question on discourse.nodered.org .  I know that some people over there yse Grafana...
Good luck!
Bart
